export const Pages = [
    {
        pageName: "Bosh sahifa",
        iconActive: "/assets/homeActive.png",
        icon: "/assets/home.png",
        path: "/",
        id: 1,
    },
    // {
    //     pageName: "Video darsliklar",
    //     iconActive: "/assets/lessonsActive.png",
    //     icon: "/assets/lessons.png",
    //     path: "/lessons",
    //     id: 2,
    // },
    {
        pageName: "Kutubxona",
        iconActive: "/assets/libraryActive.png",
        icon: "/assets/library.png",
        path: "/library",
        id: 2,
    },
    {
        pageName: "Testlar",
        iconActive: "/assets/quizActive.png",
        icon: "/assets/quiz.png",
        path: "/quiz",
        id: 3,
    },
    {
        pageName: "Vazifalar",
        iconActive: "/assets/homeworkActive.png",
        icon: "/assets/homework.png",
        path: "/homework",
        id: 4,
    },
    {
        pageName: "Peshqadamlar",
        iconActive: "/assets/liderboardActive.png",
        icon: "/assets/liderboard.png",
        path: "/liderboard",
        id: 5,
    },
    // {
    //     pageName: "Premium obuna",
    //     iconActive: "/assets/subscriptionActive.png",
    //     icon: "/assets/subscription.png",
    //     path: "/premium",
    //     id: 6,
    // },
    // {
    //     pageName: "AI Yordamchi",
    //     iconActive: "/assets/aiTutorActive.png",
    //     icon: "/assets/aiTutor.png",
    //     path: "/aiTutor",
    //     id: 7,
    // },
]