export const Pages = [
    {
        pageName: "Bosh sahifa",
        iconActive: "/assets/homeActive.png",
        icon: "/assets/home.png",
        path: "/dashboard",
        soon: false,
        id: 1,
    },
    {
        pageName: "Grammatika",
        iconActive: "/assets/grammarActive.png",
        icon: "/assets/grammar.png",
        path: "/grammar",
        soon: false,
        id: 2,
    },
    {
        pageName: "Testlar",
        iconActive: "/assets/quizActive.png",
        icon: "/assets/quiz.png",
        path: "/quiz",
        soon: false,
        id: 3,
    },
    {
        pageName: "Peshqadamlar",
        iconActive: "/assets/liderboardActive.png",
        icon: "/assets/liderboard.png",
        path: "/liderboard",
        soon: false,
        id: 4,
    },
    {
        pageName: "Video darsliklar",
        iconActive: "/assets/lessonsActive.png",
        icon: "/assets/lessons.png",
        path: "",
        soon: true,
        id: 5,
    },
    {
        pageName: "Vazifalar",
        iconActive: "/assets/homeworkActive.png",
        icon: "/assets/homework.png",
        path: "",
        soon: true,
        id: 6,
    },
    {
        pageName: "Kutubxona",
        iconActive: "/assets/libraryActive.png",
        icon: "/assets/library.png",
        path: "",
        soon: true,
        id: 7,
    },
    {
        pageName: "Premium obuna",
        iconActive: "/assets/subscriptionActive.png",
        icon: "/assets/subscription.png",
        path: "",
        soon: true,
        id: 8,
    },
    {
        pageName: "AI Yordamchi",
        iconActive: "/assets/aiTutorActive.png",
        icon: "/assets/aiTutor.png",
        path: "",
        soon: true,
        id: 9,
    },
]