export const Pages = [
    {
        pageName: "Bosh sahifa",
        iconActive: "/assets/homeActive.png",
        icon: "/assets/home.png",
        path: "/",
        id: 1,
    },
    {
        pageName: "Video darsliklar",
        iconActive: "/assets/lessonsActive.png",
        icon: "/assets/lessons.png",
        path: "/lessons",
        id: 2,
    },
    {
        pageName: "Kutubxona",
        iconActive: "/assets/libraryActive.png",
        icon: "/assets/library.png",
        path: "/library",
        id: 3,
    },
    {
        pageName: "Testlar",
        iconActive: "/assets/quizActive.png",
        icon: "/assets/quiz.png",
        path: "/quiz",
        id: 4,
    },
    {
        pageName: "Uyga Vazifa",
        iconActive: "/assets/homeworkActive.png",
        icon: "/assets/homework.png",
        path: "/homework",
        id: 5,
    },
    {
        pageName: "Peshqadamlar",
        iconActive: "/assets/liderboardActive.png",
        icon: "/assets/liderboard.png",
        path: "/liderboard",
        id: 6,
    },
    {
        pageName: "AI Yordamchi",
        iconActive: "/assets/aiTutorActive.png",
        icon: "/assets/aiTutor.png",
        path: "/aiTutor",
        id: 7,
    },
    {
        pageName: "Premium obuna",
        iconActive: "/assets/subscriptionActive.png",
        icon: "/assets/subscription.png",
        path: "/subscription",
        id: 8,
    },
]